#!/usr/bin/env python3
"""Captive-portal redirect for the hotspot Pi.

Every HTTP request on port 80 is answered with a redirect to the control page:
a phone's connectivity probe lands here (pi/setup.sh points the hotspot's DNS at
the Pi for every name), the OS shows its "sign in to network" prompt, and that
opens the page. It also makes http://10.42.0.1 work without the port. Stdlib
only, runs as the pi user, rsm-portal.service grants CAP_NET_BIND_SERVICE.

With a certificate (a combined key+cert PEM, generated by pi/setup.sh) it also
listens on 443, so https://10.42.0.1 redirects too, after the browser's
self-signed-certificate warning is accepted once per phone. Https to any other
name can't work, the Pi can't hold a valid certificate for someone else's
domain, that's TLS doing its job.

    python3 pi/portal.py PAGE_URL [port] [pemfile]      port defaults to 80

The page URL comes from rsm-portal.service, where pi/setup.sh writes the hotspot
address it configured, so there is one source of truth for it.
"""

from __future__ import annotations

import os
import ssl
import sys
import threading
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer


class Redirect(BaseHTTPRequestHandler):
    page = ""  # set in main()

    def do_GET(self) -> None:
        self.send_response(HTTPStatus.FOUND)
        self.send_header("Location", self.page)
        self.send_header("Content-Length", "0")
        self.end_headers()

    do_HEAD = do_POST = do_GET

    def log_message(self, *_: object) -> None:
        pass  # phones probe every few seconds, keep the journal quiet


class QuietServer(ThreadingHTTPServer):
    def handle_error(self, *_: object) -> None:
        pass  # TLS handshakes dropped at the certificate warning are routine


def main(argv: list[str]) -> None:
    if len(argv) < 2:
        sys.exit(f"usage: {argv[0]} PAGE_URL [port] [pemfile]")
    Redirect.page = argv[1]
    port = int(argv[2]) if len(argv) > 2 else 80
    server = QuietServer(("", port), Redirect)
    if len(argv) > 3 and os.path.exists(argv[3]):  # no cert, http only
        context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        context.load_cert_chain(argv[3])
        https = QuietServer(("", 443), Redirect)
        https.socket = context.wrap_socket(https.socket, server_side=True)
        threading.Thread(target=https.serve_forever, daemon=True).start()
    server.serve_forever()


if __name__ == "__main__":
    main(sys.argv)
